apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: frontend 
  template: 
    metadata:
      name: frontend
      labels: 
        app: frontend
    spec:
      containers:
      - name: frontend
        image: eurovision-frontend:dev
        ports: 
        - containerPort: 3000
          protocol: TCP


