apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: db
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: db 
  template: 
    metadata:
      name: db
      labels: 
        app: db
    spec:
      containers:
      - name: db
        image: eurovision-db:dev
        ports: 
        - containerPort: 5432
          protocol: TCP
        envFrom:
        - secretRef: 
            name: postgres-creds
        env:
        - name: POSTGRES_DB
          value: eurovision
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - apiVersion: v1 
    kind: PersistentVolumeClaim
    metadata:
      name: data 
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
